#!/usr/bin/env python3

print("Social Media CLI - Available Commands")
print("=====================================")
print()
print("1. Login to a social media platform:")
print("   socialmedia-cli login <platform>")
print("   Example: socialmedia-cli login twitter")
print()
print("2. Post a message directly:")
print("   socialmedia-cli post-text <platform> <message>")
print("   Example: socialmedia-cli post-text twitter 'Hello world!'")
print()
print("3. Generate a daily digest:")
print("   socialmedia-cli digest <topic> [options]")
print("   Example: socialmedia-cli digest 'AI news' --hours 24 --tweets 5")
print()
print("4. List draft files:")
print("   socialmedia-cli drafts [category]")
print("   Example: socialmedia-cli drafts digest")
print()
print("5. Post a draft (not implemented yet):")
print("   socialmedia-cli post <draft_id>")
print()
print("Setup Instructions:")
print("==================")
print("1. Activate virtual environment:")
print("   source venv/bin/activate")
print()
print("2. Login to Twitter (first time):")
print("   socialmedia-cli login twitter")
print()
print("3. Post a tweet:")
print("   socialmedia-cli post-text twitter 'Your tweet message here'")
print()
print("Note: The CLI has compatibility issues with the current typer version.")
print("You may need to run commands directly with Python:")
print("   python -c \"from socialmedia_cli.auth import login; login('twitter')\"")
print("   python -c \"from socialmedia_cli.api import post; post('twitter', 'Hello world!')\"") 